#=========================CheckAutoSoup=========================
#=========================By : VinyyHD==========================
#===============================================================
Permission: "&cYou do not have permission to do that!"
Use: "&bUse /CheckAS [player] to check the player"
MessageCheck : "&6-> §bThe Player &4@PLAYER2 &bdrank &c&l@SOUP/1 Soups"
#===============================================================
#===============================================================
#===============================================================